name: xeus-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.9
  - xeus-python
  - ipycanvas
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - openpyxl
  - python-calamine
  - pdfminer