name: xeus-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - openpyxl
  - pdfminer
  - spacy
  - pip:
    - es-core-news-md